// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfqHAsmCjSxkF7f7Mdo_h7P7eRe9-jGIs',
    appId: '1:195552466479:web:3b1caf9571cb23204d98da',
    messagingSenderId: '195552466479',
    projectId: 'whatsap-726c4',
    authDomain: 'whatsap-726c4.firebaseapp.com',
    storageBucket: 'whatsap-726c4.appspot.com',
    measurementId: 'G-7XHRE0MCPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUSMFrjONwxE8YwcSSNEUMiuI0GfGcSS0',
    appId: '1:195552466479:android:47b372e82066b7884d98da',
    messagingSenderId: '195552466479',
    projectId: 'whatsap-726c4',
    storageBucket: 'whatsap-726c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCabIBNai_A0RupwLm9sbC1tlATZuczUPs',
    appId: '1:195552466479:ios:08ff0a56863d70d54d98da',
    messagingSenderId: '195552466479',
    projectId: 'whatsap-726c4',
    storageBucket: 'whatsap-726c4.appspot.com',
    iosBundleId: 'com.example.whatsap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCabIBNai_A0RupwLm9sbC1tlATZuczUPs',
    appId: '1:195552466479:ios:c1c3ee226b46031c4d98da',
    messagingSenderId: '195552466479',
    projectId: 'whatsap-726c4',
    storageBucket: 'whatsap-726c4.appspot.com',
    iosBundleId: 'com.example.whatsap.RunnerTests',
  );
}
